Implemented Mute/Unmute button
WiktoriaKrzyzanska/PIO6_MoneyLand pull request #2
Opened 2023-05-21 20:06 UTC by brzezin0

2023-05-21 20:35 UTC, JuliaTrzebuchowska approved these changes, later dismissed
fajnie fajnie haj

2023-05-21 20:45 UTC, Ikar17 commented
![bug](https://github.com/WiktoriaKrzyzanska/PIO/assets/90191525/b375635c-a727-4997-aee1-3e3ca112a3a7)
Duplikacja ikony przy zmaksymalizowaniu okna.

2023-05-23 08:59 UTC, Vittoriio requested changes
jest dobrze wszystko jest w porządku

2023-05-23 09:01 UTC, brzezin0 commented
> Do poprawy

Dzięki za informację. Pozdrawiam z rodzinką

2023-05-23 19:03 UTC, WiktoriaKrzyzanska commented
Ok. It's working fine. Possible future fix - changing type of cursor when hovering on icon. Needs rebase though

2023-05-24 08:52 UTC, JuliaTrzebuchowska approved these changes
rebase next time ;)

2023-05-24 08:52 UTC, merged